### PR TITLE
Add missing rosterver stream feature from RFC-6121

### PR DESCRIPTION
**Pull request by rufferson**
It appears the namespace mentioned in RFC6121 2.6.1 is not in the registry. 
This PR is to add the missing namespece.

### CODE REVIEW

**Comment by SamWhited** [comment]
Good catch; thanks! I'm not actually sure if this needs to be in the namespaces registry if it's already in the features registry; I'll try to find out and let you know.

**Comment by SamWhited** [comment]
Merged as c8c6036; I tried resolving some conflicts using GitHub's built in tooling, but as usual it broke things so you may need to hard reset your master branch before making any other PRs since you made the PR from there. Thanks again!

**Comment by rufferson** [comment]
oops, sorry i forgot to check other pending PRs to align versioning. Will keep in mind.

**Comment by SamWhited** [comment]
I wouldn't worry about it; you never know what order PRs are going to be merged in anyways :)

**Pull request closed without merging**
