### PR TITLE
xdv-prefixes: Add prefix for pubsub integer-or-max

### PR DESCRIPTION
**Pull request by Zash**
A prefix is needed. Here's a prefix. Probelm solved. Open to bikeshedding the prefix, but please do so on the standards@ list.

### CODE REVIEW

**Comment by ghost** [comment]
Any update on this? Can this be merged?

**Comment by SamWhited** [comment]
Did discussion ever happen on this prefix? It seems good to me, but if no discussion happened I'd like to raise it on list before merging.

**Comment by Zash** [comment]
Feel free to raise on the list.

**Comment by SamWhited** [comment]
Nah, LGTM (the more I think about it the more it seems unnecessary). Sorry for the long delay.

**Comment by Zash** [comment]
Thanks @SamWhited for taking on the registrar role!

**Pull request merged**
