### PR TITLE
stream features: add entity caps

### PR DESCRIPTION
**Pull request by SamWhited**
Blocking on xsf/xeps#257

### CODE REVIEW

**Comment by linkmauve** [comment]
I already opened #6, doing almost exactly the same thing with a slight variation in naming.

Unrelated question, what should the <name/> be in this case?  I see “Server Dialback” like that, but the rest seem to have a more XEP-related name.

**Comment by SamWhited** [comment]
@linkmauve oops, my mistake; thanks! Not sure what the standard practice for naming is; I'll see if I can't find anything on it.

**Comment by stpeter** [comment]
I would prefer to use the shortname (i.e., "caps"). I'm not sure why we didn't do that for XEP-0220, but I'd propose changing it to match the others.

**Comment by linkmauve** [comment]
Just fyi @SamWhited, you can reopen a PR instead of creating a new one, it makes history clearer.

**Comment by SamWhited** [comment]
@linkmauve yah, I probably should have done that; forgot about the other one I created. Thanks!

**Pull request closed without merging**
